# Generated by Django 4.1.2 on 2022-10-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_comment_comment_text_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
